### ISSUE TITLE
Fix up funding acknowledgement to make site nice again

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/cbbs-imaging-docs#13]
Current approach breaks any mobile display.

This also points to the fact that we should have the ability to preview a PR visually, and not just the code. Otherwise the autobuild feature is pretty much useless, as one would need to build locally to avoid issues as this one prior a merge.

**Comment by aqw** [comment]
In general, the site needs mobile love. I put *zero* effort into it. It shouldn't be that hard, but nav will take a bit of focus.

Unless you @bpoldrack are interested in it, I can take a whack at it on the IPSY docs site and port over fixes to here.

---Alex
