### ISSUE TITLE
How can I force-update the rendered site, and or debug what is going on?

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/cbbs-imaging-docs#17]
I made a straight push into master with more place holders. I was expecting the site to get updated, but that doesn't seem to be the case. Or rather, it is in some strange state of half-updated: The changes content on pre-existing pages is visible, but none of the new pages show up.

It would be good to have a doc in this repo that gives a few insights in where this is hosted, how it is built, and a convenience link to the travis logs. People looking into the makefile will assume that it lives on kumo, which is does not.

**Comment by bpoldrack** [comment]
Outcommented unused stuff in Makefile: 4fb63ed63c4722894428d9b04414d31356feb03b
Added standard Travis button to README: 77a7e774bab70b96ed03f9a77672d87da1a3f881

**Comment by mih** [comment]
Thanks!
