### ISSUE TITLE
Create page category for data acquisition devices

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/cbbs-imaging-docs#9]
Each device should have its own page, identify whom to talk to, and basic info.

**Comment by bpoldrack** [comment]
Such a section is available with PR #12.

We should use this issue to make a list of relevant devices. We need to know at least a "name" like `7T Siemens Magnetom` and a location where to find it, to specify them.
From the survey we have:

- 7T Siemens Magnetom
- 3T Siemens Verio
- 3T Siemens Skyra
- 3T Siemens Prisma
- 3T Philips Achieva

and added by survey responders:
- MEG
- 4.7 lin animal scanner
- future 9.4 lin animal scanner

**Comment by mih** [comment]
We have that.
